version: '3.8'

services:
  mongodb:
    container_name: db-vouch
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  app:
    depends_on:
      - mongodb
    image: chat-svc
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      NX_API_PORT: 8080
      NX_MONGO_URL: mongodb://mongodb:27017
      NX_MONGO_INITDB_DATABASE: vouch-db
      NX_JWT_KEY: vouch-key
    stdin_open: true
    tty: true

  web-chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - "3000:3000"
    environment:
      API_URL: localhost:8080/api
    restart: unless-stopped

volumes:
  mongo_data: {}
